apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: backend
  namespace: default
spec:
  owner:
    projectName: habitual

  componentType:
    name: deployment/service
    kind: ClusterComponentType

  autoDeploy: true

  parameters:
    port: 8080
